### ISSUE TITLE
[request change] Not using correct MongoDB commands

### ISSUE THREAD

**Issue by guyspy** [hsinyichiu102/vertx-Coroutine-kotlin#4]
Please refer to the original assignment
![截圖 2021-01-28 下午2 21 25](https://user-images.githubusercontent.com/1080420/106098623-4fed8980-6174-11eb-92fa-e53baff65787.png)

You're not using any of these beautiful commands at all. Such a pity.
Please fix this.

**Comment by hsinyichiu102** [comment]
Hi,
I had tried the aggragate to get the average of the rating score. But I've searched to check if I can use any method to get the shell operation in the code. In order to provide the average number at least. What I decided was just iterate all the numbers and calculate them.
I've changed the code to aggregation as below firstly and keep checking the setting and libraries to get the average.

```
  suspend fun getRating(ctx: RoutingContext) {
      val movie_id = ctx.pathParam("movie_id")
      val query = client.find("movie",JsonObject().put("movie_id", movie_id)).await()
      // cannot get "$avg" works with this aggregate
      val score= client.aggregate("average", query.get(0).getJsonArray("rating"))

      ctx.response().end(json {
          obj(
                  "movie_id" to movie_id,
                  "rating_avg" to score)
                  .encode()
      })
    }
```

**Comment by guyspy** [comment]
OK! You've looked into mongodb shell command! That will be enough for the purpose of this test.
vertx' mongo driver lacks a lot of features, so don't bother if you cannot use the command via this client.
